apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ .Values.configMap.name }} 
data: 
  index.html: |
    <!DOCTYPE html>
    <html lang="ru">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Лучший в мире подкаст</title>
    <style>
        body {
            background-color: #FFFF;
            color: pink;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            text-align: center;
            margin: 0;
            padding: 0;
        }
        h1 {
            margin-top: 50px;
            font-size: 5rem; 
        }
        p {
            font-size: 1.2rem; 
        }
        a {
            color: pink;
            text-decoration: none;
            font-size: 1.2rem;
        }
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100%;
        }
        .image-link {
            margin: 20px 0;
        }
        img {
            max-width: 70%;
            height: auto;
            border: 5px solid pink;
            border-radius: 10px;
        }
    </style>
    </head>
    <body>
    <div class="container">
        <h1>Слушайте подкаст на всех плаформах</h1>
        <div class="image-link">
            <a href="https://music.yandex.ru/album/30682370?utm_medium=copy_link" target="_blank">
                <img src="podcast.jpg" alt="Ссылка на подкаст">
            </a>
        </div>
        <a href="https://music.yandex.ru/album/30682370?utm_medium=copy_link" target="_blank"></a>
    </div>
    </body>
    </html>