FROM ubuntu:24.04

RUN apt-get update && apt-get install -y 
python3 python3-pip \    
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip3 install -r /app/requirements.txt

COPY my_app.py /app/

RUN useradd -ms /bin/bash appuser
USER appuser

WORKDIR /app

CMD ["python3", "my_app.py"]
